[project]
name = "song"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "KyvYang", email = "kyvyang@foxmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.11.2",
    "moviepy>=2.2.1",
    "numpy>=2.5.3",
    "opencv-python-headless>=5.0.0.93",
    "pygame>=2.6.1",
    "scipy>=1.18.1",
]

[project.scripts]
song = "song:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
